# Generated by Django 2.0.4 on 2018-04-19 14:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='noticia',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('categoria', models.CharField(max_length=30)),
                ('titulo', models.CharField(max_length=300)),
                ('slug', models.SlugField()),
                ('subtitulo', models.CharField(max_length=300)),
                ('data', models.DateTimeField(auto_now_add=True)),
                ('autor', models.CharField(max_length=50)),
                ('foto1', models.CharField(max_length=30)),
                ('paragrafo1', models.TextField()),
                ('foto2', models.CharField(max_length=30)),
                ('paragrafo2', models.TextField()),
            ],
        ),
    ]
