# Generated by Django 2.0.4 on 2018-04-19 17:33

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='noticia',
            name='capa',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='autor',
            field=models.CharField(default='Redação', max_length=50),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='categoria',
            field=models.CharField(default='Geral', max_length=30),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='slug',
            field=models.SlugField(max_length=300),
        ),
    ]
