# Generated by Django 2.0.4 on 2018-04-19 17:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0002_auto_20180419_1433'),
    ]

    operations = [
        migrations.AlterField(
            model_name='noticia',
            name='foto1',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='foto2',
            field=models.CharField(blank=True, max_length=30),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='paragrafo1',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='paragrafo2',
            field=models.TextField(blank=True),
        ),
        migrations.AlterField(
            model_name='noticia',
            name='subtitulo',
            field=models.CharField(blank=True, max_length=300),
        ),
    ]
